### ISSUE TITLE
Excessive recompilation of compilation units.

### ISSUE THREAD

**Issue by j-jorge** [dcourtois/premake-compilationunit#3]
The `__compilation_unit__x.cpp` files are rewritten each time premake is run, even if their content does not change. This cause the compilation units to be compiled every time premake and make are run, although nothing should be done.

**Comment by dcourtois** [comment]
Hi, first of all, thanks for reporting this issue ! And secondly : you're entirely right, and as soon as I get some time to work on it, I'll fix this (should be done in a day or two)

**Comment by dcourtois** [comment]
Sorry for the delay, it slipped out of my mind ! It should be fixed by commit fbdb30590da8dabd3885a54aff985e48bf7fe600
Feel free to tell if there is any problem.

**Comment by j-jorge** [comment]
It works perfectly, thanks!
