### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by JackBister** [dcourtois/premake-compilationunit#6]
Hi!

Would you mind adding a license to this repo to clarify what the terms of using it are? It's an awesome plugin, but without any license you kind of have to assume the worst and it makes it scary to fork and change anything in it.

Also, is there currently a way to exclude individual files from being included in the generated cpp files but still have them included in the build? I went through the source but I wasn't quite sure how the fileconfig stuff works in premake and can't seem to find any documentation about it. Using a filter and setting compilationunitenabled to false inside it did not seem to work.

Thank you for your time.

**Comment by dcourtois** [comment]
Hi, for the license stuff, the absence of one is kind of a "do what you want with this at your own risk", but I'll try to find one that's a bit more "legal" if it's really necessary.

And for the exclusion of specific files, it should be working using filters. Something like this:

```
filter {}
    compilationunitenabled true
filter "files:sources/some_file.cpp"
    compilationunitenabled false
```

This should result in `some_file.cpp` being compiled separately from the generated compilation units.
If it doesn't work like this, it's a bug, and you should create another dedicated issue :)
(I'm usually working on Visual Studio, so even though my addons are meant to be "action" agnostic, there might be some specifics to other actions (like gmake or whatever) that don't work well with the addon)

**Comment by JackBister** [comment]
Ah, I got the filter working now, I was being a dummy and just using the file name without the directory.

Yeah, I think it would be good to add some license statement at least just to make it clear that it is a "do whatever you want" deal. Maybe the ["Unlicense"](https://unlicense.org/)?

**Comment by dcourtois** [comment]
I was working on another project where licenses were mandatory and I must say that I really hated the fact that common sense couldn't be the default one when none was available, so I searched a bit and found the perfect one at the time: http://www.wtfpl.net/

Now I realize that you might take this as a joke, but if it's ok with you, I'd like to choose this one. It's the one closest to what I think and what my philosophy is regarding open source development. Just tell me if it's ok with you.

**Comment by JackBister** [comment]
That sounds ok to me :)
